version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
        - mongodb:/data/db
  backend:
    container_name: backend
    build:
      context: './too-doo-api'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  frontend:
    container_name: frontend
    build:
      context: './too-doo-frontend'
      dockerfile: Dockerfile
    ports:
      - 80:3000
volumes:
  mongodb: