version: '3.8'
services:
  mongodb_service:
    image: mongo
    ports:
      - 27017:27017
    volumes:
        - mongodb:/data/db
  node:
    image: backend
    build:
      context: './too-doo-api'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb_service
  frontend:
    image: frontend
    build:
      context: './too-doo-frontend'
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - node
volumes:
  mongodb: